-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 01:33:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio_bd` DEFAULT CHARACTER SET utf8 ;
USE `portfolio_bd` ;

-- -----------------------------------------------------
-- Table `portfolio_bd`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_bd`.`user` (
  `DNI` INT NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_bd`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_bd`.`persona` (
  `user_DNI` INT NOT NULL,
  `fname` VARCHAR(45) NULL,
  `sname` VARCHAR(45) NULL,
  `birth_date` DATE NULL,
  `location` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `photo_url` VARCHAR(100) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`user_DNI`),
  INDEX `fk_persona_user1_idx` (`user_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_persona_user1`
    FOREIGN KEY (`user_DNI`)
    REFERENCES `portfolio_bd`.`user` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_bd`.`social`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_bd`.`social` (
  `persona_user_DNI` INT NOT NULL,
  `platform` VARCHAR(20) NULL,
  `url_logo` VARCHAR(100) NULL,
  `url` VARCHAR(100) NULL,
  PRIMARY KEY (`persona_user_DNI`),
  INDEX `fk_social_persona1_idx` (`persona_user_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_social_persona1`
    FOREIGN KEY (`persona_user_DNI`)
    REFERENCES `portfolio_bd`.`persona` (`user_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_bd`.`about`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_bd`.`about` (
  `persona_user_DNI` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(240) NULL,
  `interest` VARCHAR(240) NULL,
  `history` VARCHAR(240) NULL,
  `tag` VARCHAR(10) NULL,
  PRIMARY KEY (`persona_user_DNI`),
  INDEX `fk_about_persona1_idx` (`persona_user_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_about_persona1`
    FOREIGN KEY (`persona_user_DNI`)
    REFERENCES `portfolio_bd`.`persona` (`user_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_bd`.`job_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_bd`.`job_type` (
  `id` INT NOT NULL,
  `job_type` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_bd`.`job_experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_bd`.`job_experience` (
  `id` INT NOT NULL,
  `persona_user_DNI` INT NOT NULL,
  `job` VARCHAR(45) NULL,
  `description` VARCHAR(240) NULL,
  `workplace` VARCHAR(45) NULL,
  `logo_url` VARCHAR(100) NULL,
  `location` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `start` INT NULL,
  `end` INT NULL,
  `current` TINYINT(1) NULL,
  `job_type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_user_DNI`, `job_type_id`),
  INDEX `fk_job_experience_job_type1_idx` (`job_type_id` ASC) VISIBLE,
  INDEX `fk_job_experience_persona1_idx` (`persona_user_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_job_experience_job_type1`
    FOREIGN KEY (`job_type_id`)
    REFERENCES `portfolio_bd`.`job_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_experience_persona1`
    FOREIGN KEY (`persona_user_DNI`)
    REFERENCES `portfolio_bd`.`persona` (`user_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_bd`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_bd`.`skills` (
  `skill` VARCHAR(45) NOT NULL,
  `score` INT NULL,
  `tag` VARCHAR(20) NULL,
  `icon_url` VARCHAR(100) NULL,
  `persona_user_DNI` INT NOT NULL,
  PRIMARY KEY (`skill`, `persona_user_DNI`),
  INDEX `fk_skills_persona1_idx` (`persona_user_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_skills_persona1`
    FOREIGN KEY (`persona_user_DNI`)
    REFERENCES `portfolio_bd`.`persona` (`user_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_bd`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_bd`.`projects` (
  `id` INT NOT NULL,
  `persona_user_DNI` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(240) NULL,
  `release` VARCHAR(45) NULL,
  `url` VARCHAR(100) NULL,
  `thumb` VARCHAR(100) NULL,
  `tag` VARCHAR(20) NULL,
  PRIMARY KEY (`id`, `persona_user_DNI`),
  INDEX `fk_projects_persona1_idx` (`persona_user_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_projects_persona1`
    FOREIGN KEY (`persona_user_DNI`)
    REFERENCES `portfolio_bd`.`persona` (`user_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_bd`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_bd`.`tags` (
  `tag` VARCHAR(45) NOT NULL,
  `about_id` INT NOT NULL,
  `about_persona_id` INT NOT NULL,
  `skills_skill` VARCHAR(45) NOT NULL,
  `skills_persona_id` INT NOT NULL,
  `projects_id` INT NOT NULL,
  `projects_persona_id` INT NOT NULL,
  PRIMARY KEY (`about_id`, `about_persona_id`, `tag`, `skills_skill`, `skills_persona_id`, `projects_id`, `projects_persona_id`),
  INDEX `fk_tags_skills1_idx` (`skills_skill` ASC, `skills_persona_id` ASC) VISIBLE,
  INDEX `fk_tags_projects1_idx` (`projects_id` ASC, `projects_persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_tags_skills1`
    FOREIGN KEY (`skills_skill`)
    REFERENCES `portfolio_bd`.`skills` (`skill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `portfolio_bd`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_bd`.`education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_bd`.`education` (
  `persona_user_DNI` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `institute` VARCHAR(45) NULL,
  `logo_url` VARCHAR(100) NULL,
  `description` VARCHAR(240) NULL,
  `degree` VARCHAR(45) NULL,
  `scrore` DOUBLE NULL,
  `start` INT NULL,
  `end` INT NULL,
  `current` TINYINT NULL,
  PRIMARY KEY (`persona_user_DNI`),
  INDEX `fk_Education_persona1_idx` (`persona_user_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_Education_persona1`
    FOREIGN KEY (`persona_user_DNI`)
    REFERENCES `portfolio_bd`.`persona` (`user_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
